apiVersion: velero.io/v1
kind: Backup
metadata:
  name: LOL-BACKUP
  namespace: velero
spec:
  excludedResources:
  - pvc
  includedNamespaces:
  - LOL
  includedResources:
  - '*'
  storageLocation: default
  ttl: 72h0m0s
