apiVersion: velero.io/v1
kind: Backup
metadata:
  name: ic-kilanytry7-BACKUP-20210805-124230
  namespace: velero
spec:
  excludedResources:
  - pvc
  includedNamespaces:
  - ic-kilanytry7
  includedResources:
  - '*'
  storageLocation: default
  ttl: 24h0m0s
