apiVersion: velero.io/v1
kind: Backup
metadata:
  name: ic-incorta-argo-BACKUP
  namespace: velero
spec:
  excludedResources:
  - pvc
  includedNamespaces:
  - ic-incorta-argo
  includedResources:
  - '*'
  storageLocation: default
  ttl: 24h0m0s
