apiVersion: velero.io/v1
kind: Backup
metadata:
  name: ic-something-BACKUP-20210805-110751
  namespace: velero
spec:
  excludedResources:
  - pvc
  includedNamespaces:
  - ic-something
  includedResources:
  - '*'
  storageLocation: default
  ttl: 24h0m0s
