apiVersion: velero.io/v1
kind: Backup
metadata:
  name: ic-kilanytry3-BACKUP
  namespace: velero
spec:
  excludedResources:
  - pvc
  includedNamespaces:
  - ic-kilanytry3
  includedResources:
  - '*'
  storageLocation: default
  ttl: 72h0m0s
