apiVersion: velero.io/v1
kind: Backup
metadata:
  name: ic-noureen-central-1-backup-20220124-190043
  namespace: velero
spec:
  includedNamespaces:
  - ic-noureen-central-1
  includedResources:
  - '*'
  storageLocation: default
  ttl: 72h0m0s
