apiVersion: velero.io/v1
kind: Backup
metadata:
  name: ic-my-clust-backup
  namespace: velero
spec:
  excludedResources:
  - pvc
  includedNamespaces:
  - ic-my-clust
  includedResources:
  - '*'
  storageLocation: default
  ttl: 72h0m0s
