apiVersion: velero.io/v1
kind: Backup
metadata:
  name: ic-ayasbigtest-backup
  namespace: velero
spec:
  excludedResources:
  - pvc
  includedNamespaces:
  - ic-ayasbigtest
  includedResources:
  - '*'
  storageLocation: default
  ttl: 24h0m0s
