apiVersion: velero.io/v1
kind: Backup
metadata:
  name: ic-meow10-BACKUP
  namespace: velero
spec:
  excludedResources:
  - pvc
  includedNamespaces:
  - ic-meow10
  includedResources:
  - '*'
  storageLocation: default
  ttl: 72h0m0s
