apiVersion: velero.io/v1
kind: Backup
metadata:
  name: ic-aug19v2-stg-backup
  namespace: velero
spec:
  excludedResources:
  - pvc
  includedNamespaces:
  - ic-aug19v2-stg
  includedResources:
  - '*'
  storageLocation: default
  ttl: 72h0m0s
