apiVersion: velero.io/v1
kind: Backup
metadata:
  name: ic-new-clus-01-backup
  namespace: velero
spec:
  excludedResources:
  - pvc
  includedNamespaces:
  - ic-new-clus-01
  includedResources:
  - '*'
  storageLocation: default
  ttl: 72h0m0s
