apiVersion: velero.io/v1
kind: Backup
metadata:
  name: ic-nehal-30-backup
  namespace: velero
spec:
  excludedResources:
  - pvc
  includedNamespaces:
  - ic-nehal-30
  includedResources:
  - '*'
  storageLocation: default
  ttl: 72h0m0s
