apiVersion: velero.io/v1
kind: Backup
metadata:
  name: ic-ayatestingsth13-backup
  namespace: velero
spec:
  excludedResources:
  - pvc
  includedNamespaces:
  - ic-ayatestingsth13g
  includedResources:
  - '*'
  storageLocation: default
  ttl: 72h0m0s
