apiVersion: velero.io/v1
kind: Backup
metadata:
  name: ic-ayasdisktest-backup-20211217-190635
  namespace: velero
spec:
  includedNamespaces:
  - ic-ayasdisktest
  includedResources:
  - '*'
  storageLocation: default
  ttl: 24h0m0s
