apiVersion: velero.io/v1
kind: Backup
metadata:
  name: ic-tryingcapitalls-backup-20210930-051248
  namespace: velero
spec:
  excludedResources:
  - pvc
  includedNamespaces:
  - ic-tryingcapitalls
  includedResources:
  - '*'
  storageLocation: default
  ttl: 48h0m0s
